apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    build: tomcat-demo
  name: tomcat-demo
  namespace: consaff-tomcat-demo
spec:
  lookupPolicy:
    local: false
status:
  dockerImageRepository: image-registry.openshift-image-registry.svc:5000/consaff-tomcat-demo/tomcat-demo
